{% set pyproject = load_file_data('../../../pyproject.toml', from_recipe_dir=True) %}
{% set buildsystem = pyproject['build-system'] %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ../../../dist/{{ name }}-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    {% for group,epoints in project.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in buildsystem['requires'] %}
    - {{ dep }}
    {% endfor %}

  run:
    - python {{ project['requires-python'] }}
    {% for dep in project.get('dependencies', []) %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    {% for dep in project['optional-dependencies']['tests'] %}
    - {{ dep }}
    {% endfor %}
    {% for dep in project['optional-dependencies']['cmd'] %}
    - {{ dep }}
    {% endfor %}
  source_files:
    - pyproject.toml
  imports:
    - {{ project["name"] }}
  commands:
    - pytest -v --pyargs pyct
    - pyct --help
    - pyct --version
    - pyct report --help
    - pyct report pyct python

about:
  home: {{ project['urls']['Homepage'] }}
  summary: {{ project['description'] }}
  license: {{ project['license'] }}
  license_file: LICENSE.txt
