{% set sdata = load_setup_py_data() %}

package:
  name: pyct
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python

requirements:
  host:
    - python
    - setuptools >=30.3.0
    - param >=1.7.0
  run:
    - python {{ sdata['python_requires'] }}
    - pyct-core ={{ sdata['version'] }}
    {% for dep in sdata['extras_require']['cmd'] %}
    - {{ dep }}
    {% endfor %}

test:
  imports:
    - pyct
    - pyct.cmd
  requires:
    {% for dep in sdata['extras_require']['tests'] %}
    - "{{ dep }}"
    {% endfor %}
  commands:
    - pytest pyct
    - pyct --help
    - pyct --version
    - pyct report --help	   
    - pyct report pyct python

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
